name: Push To Main

on:
  push:
    branches:
      - main

jobs:
  lint-test-build-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 23
      - run: npm ci
      - run: npm run lint
      - run: npm run jest
      - run: npm run test
      - run: npm run build
        env:
          CI: false
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build